-- SAFYAM CREATIVE EMPORIUM — Supabase backend schema
-- Run this in Supabase SQL Editor once.

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  name text not null,
  slug text unique,
  category text not null check (category in ('beads','fashion','accessories','gifts')),
  price numeric(12,2) not null default 0,
  compare_at numeric(12,2) not null default 0,
  badge text default '',
  featured integer not null default 99,
  active boolean not null default true,
  stock integer not null default 0,
  image_url text default '',
  image_alt text default '',
  image_credit text default '',
  description text default '',
  tags text[] not null default '{}'
);

create table if not exists public.store_settings (
  id integer primary key default 1,
  brand_name text default 'Safyam Creative Emporium',
  hero_title text default 'Crafted to be remembered.',
  hero_text text default '',
  announcement text default '',
  whatsapp text default '',
  email text default '',
  instagram text default 'https://www.instagram.com/safyam_creative/',
  updated_at timestamptz not null default now()
);

insert into public.store_settings(id) values(1) on conflict (id) do nothing;

alter table public.products enable row level security;
alter table public.store_settings enable row level security;

-- Anyone can read the live catalogue and store settings.
create policy "public read active products" on public.products for select using (active = true or auth.role() = 'authenticated');
create policy "public read store settings" on public.store_settings for select using (true);

-- Only authenticated admin users can write.
create policy "admin insert products" on public.products for insert to authenticated with check (true);
create policy "admin update products" on public.products for update to authenticated using (true) with check (true);
create policy "admin delete products" on public.products for delete to authenticated using (true);
create policy "admin update settings" on public.store_settings for insert to authenticated with check (true);
create policy "admin modify settings" on public.store_settings for update to authenticated using (true) with check (true);

-- Storage bucket for product uploads.
insert into storage.buckets (id,name,public) values ('product-images','product-images',true) on conflict (id) do update set public=true;
create policy "public product image read" on storage.objects for select using (bucket_id='product-images');
create policy "admin product image upload" on storage.objects for insert to authenticated with check (bucket_id='product-images');
create policy "admin product image update" on storage.objects for update to authenticated using (bucket_id='product-images') with check (bucket_id='product-images');
create policy "admin product image delete" on storage.objects for delete to authenticated using (bucket_id='product-images');
